#if defined(MOVABLE_LIGHT)
#define MH_TESTMERGE_LIGHT_WORKAROUND MOVABLE_LIGHT
#else
#define MH_TESTMERGE_LIGHT_WORKAROUND OVERLAY_LIGHT
#endif
#warn REMOVE MH_TESTMERGE_LIGHT_WORKAROUND BEFORE FULL MERGE!
