/obj/item/mecha_parts/mecha_equipment/examine(mob/user)
	.=..()
	if(src.movedelay)
		switch(movedelay)
			if(0.1)
				. += span_notice("This is a lightweight module.")
			if(0.2)
				. += span_notice("This module is moderately heavy.")
			if(0.3 to 0.4)
				. += span_notice("This module is rather heavy!")
	else . += span_notice("This module is effectively weightless.")
