/mob/living/Initialize(mapload)
	. = ..()
	RegisterSignals(src, list(SIGNAL_ADDTRAIT(TRAIT_TRUE_NIGHT_VISION), SIGNAL_ADDTRAIT(TRAIT_MESON_VISION), SIGNAL_ADDTRAIT(TRAIT_THERMAL_VISION), SIGNAL_ADDTRAIT(TRAIT_XRAY_VISION)), PROC_REF(update_sight))

/mob/living/Destroy()
	UnregisterSignal(src, list(SIGNAL_ADDTRAIT(TRAIT_TRUE_NIGHT_VISION), SIGNAL_ADDTRAIT(TRAIT_MESON_VISION), SIGNAL_ADDTRAIT(TRAIT_THERMAL_VISION), SIGNAL_ADDTRAIT(TRAIT_XRAY_VISION)))
	return ..()
